PartB/Models/Product.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;

namespace PartB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {     
        public int ProductID { get; set; }
        public int CategoryID { get; set; }
        [Display(Name = "Product Name")]
        public string Title { get; set; }
        [Display(Name = "Short Description")]
        public string ShortDescription { get; set; }
        [Display(Name = "Detailed Description")]
        public string LongDescription { get; set; }
        [Display(Name = "Image")]
        public string ImageUrl { get; set; }
        public decimal Price { get; set; }

        public virtual Category Category { get; set; }
    }
}

PartB/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using PartB.Models;
using PartB.Custom;

namespace PartB.Controllers
{
    public class ProductsController : Controller
    {
        private s3401071Entities db = new s3401071Entities();

        // GET: Products
        [Authorization]
        public ActionResult Index(string productCategory, string searchString)
        {
            // Search method sourced from Week 9 example code
            var CategoryList = new List<string>();

            var CatQuery = from d in db.Products
                            orderby d.Category.Title
                            select d.Category.Title;

            CategoryList.AddRange(CatQuery.Distinct());
            ViewBag.productCategory = new SelectList(CategoryList);

            var products = from p in db.Products
                           select p;

            if (!String.IsNullOrEmpty(searchString))
            {
                products = products.Where(q => q.Title.Contains(searchString));
            }

            if (!string.IsNullOrEmpty(productCategory))
            {
                products = products.Where(r => r.Category.Title == productCategory);
            }

            return View(products);
        }
       
        // GET: Products/Details/5
        [Authorization]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }
    }
}

PartB/Views/Products/Details.cshtml
@model PartB.Models.Product

@{
    ViewBag.Title = Model.Title + " Product Details";
}

<h2>@Html.DisplayFor(model => model.Title)</h2>

<div>
    <h4>Product Details</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ShortDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ShortDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LongDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LongDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ImageUrl)
        </dt>

        <dd>
            <img src=@Url.Content(Model.ImageUrl) alt="Image" />
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            &#36;@Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Category.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category.Title)
        </dd>

    </dl>
</div>

@using (Html.BeginForm("AddToCart", "Cart", new { id = Model.ProductID }))
{
    <p><strong>Qty:</strong> @Html.TextBox("qty", "", new { size = 1, @Value = 1 })</p>
    <p><input type="submit" value="Add To Cart" class="btn btn-add btn-bold" /></p>
}
@using (Html.BeginForm("Index", "Products"))
{
    <input type="submit" value="Back to List" class="btn btn-primary btn-bold" />
}

PartB/Views/Products/Index.cshtml
@model IEnumerable<PartB.Models.Product>

@{
    ViewBag.Title = "Products";
}

<h2>Products</h2>
    
@using (Html.BeginForm("Index", "Products", FormMethod.Get))
{
    <p>
        Category: @Html.DropDownList("productCategory", "All")
        &nbsp;Product Name: @Html.TextBox("searchString")
        <input type="submit" value="Filter" />
    </p>
}

@if (TempData["error"] != null) 
{ 
    <p class="text-danger">@TempData["error"]</p>
}

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ImageUrl)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Category.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ShortDescription)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) 
{
    <tr>
        <td>
            <img src=@Url.Content(item.ImageUrl) alt="Image" width="100" height="100" />
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Category.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ShortDescription)
        </td>
        <td>
            &#36;@Html.DisplayFor(modelItem => item.Price)
        </td>
        <td>
            @using (Html.BeginForm("AddToCart", "Cart", new { id = item.ProductID }))
            {
                <p><strong>Qty:</strong> @Html.TextBox("qty", "", new { size = 1, @Value = 1 })</p>
                <p><input type="submit" value="Add To Cart" class="btn btn-add btn-bold" /></p>
            }
            
            @using (Html.BeginForm("Details", "Products", new { id=item.ProductID }))
            {
                <input type="submit" value="View Details" class="btn btn-primary btn-bold"/>
            }
        </td>
    </tr>
}

</table>