PartB/Controllers/CheckoutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PartB.Models;
using PartB.Custom;

namespace PartB.Controllers
{
    public class CheckoutController : Controller
    {
        private StoreEntities se = new StoreEntities();

        // GET: Checkout        
        public ActionResult Index()
        {
            return RedirectToAction("OrderCheckout");                           
        }

        [Authorization]
        public ActionResult OrderCheckout()
        {
            Cart cart = Session["Cart"] as Cart;

            // Check if cart has any items in it
            if (cart.cartItems.Any())
            {
                Session["Cart"] = cart;
                return View();
            }
            else
            {
                return RedirectToAction("Index", "Cart");
            }            
        }

        // Method to create an order object and write to database
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult OrderCheckout([Bind(Include = "fullName,streetAddress,city,state,postcode")] Order order) 
        {
            if (ModelState.IsValid)
            {                              
                Cart cart = Session["Cart"] as Cart;

                // Copy cart item details to create order items
                foreach (var item in cart.cartItems)
                {
                    var orderItem = new OrderItem()
                    {
                        orderID = order.orderID,
                        productName = item.product.Title,
                        productQty = item.quantity,
                        productSubtotal = item.subtotal
                    };
                    
                    se.OrderItems.Add(orderItem);
                }

                // Fill in rest of order details
                order.totalPrice = cart.total;
                order.orderDate = DateTime.Now;
                order.customerID = Convert.ToInt32(Session["ID"]);

                se.Orders.Add(order);
                se.SaveChanges();

                // Empty cart
                cart.cartItems.Clear();
                Session["Cart"] = cart;

                return RedirectToAction("OrderSuccessful", new { id = order.orderID, cid = order.customerID});
            }
            return View(order);
        }

        public ActionResult OrderSuccessful(int id, int cid) 
        {
            int v = Convert.ToInt32(Session["ID"]);
            
            // Check if customer session is the same, redirect if not
            if (v == cid)
            {
                // Return the order
                var order = se.Orders.FirstOrDefault(o => o.orderID == id);

                var match = from a in se.OrderItems
                            where a.orderID == id
                            select a;

                // Find relevant items of the order and remove if duplicates exist
                if (match != null) 
                {
                    foreach (var item in match) 
                    {
                        if (!order.itemList.Contains(item))
                            order.itemList.Add(item);
                    }
                }
                
                return View(order);
            }
            else 
            {
                return RedirectToAction("Index", "Home");
            } 
        }
    }
}

PartB/Views/Checkout/OrderCheckout.cshtml
@model PartB.Models.Order

@{
    ViewBag.Title = "Order Checkout";
}

<script type="text/javascript" src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.payment.js"></script>
<script type="text/javascript">

    // Using jquery.payment.js plugin for Credit Card validation
    jQuery(function ($) {
        // Hide error messages
        $('#cc-number-error').hide();
        $('#cc-exp-error').hide();
        $('#cc-cvc-error').hide();

        // Format credit card fields
        $('.cc-number').payment('formatCardNumber');
        $('.cc-exp').payment('formatCardExpiry');
        $('.cc-cvc').payment('formatCardCVC');

        $('#btnConfirm').click(function (e) {
            var validcc = $.payment.validateCardNumber($('input.cc-number').val()),
                validexp = $.payment.validateCardExpiry($('input.cc-exp').payment('cardExpiryVal')),
                validcvc = $.payment.validateCardCVC($('input.cc-cvc').val());

            if (!validcc)
            {
                $('#cc-number-error').show();
                return false;
            }
            else {
                $('#cc-number-error').hide();
            }

            if (!validexp) {
                $('#cc-exp-error').show();
                return false;
            }
            else
            {
                $('#cc-exp-error').hide();
            }

            if (!validcvc) {
                $('#cc-cvc-error').show();
                return false;
            }
            else
            {
                $('#cc-cvc-error').hide();
            }

            if (validcc && validcvc && validexp)
            {
                return true;
            }
            
        });
    });
</script>
<h2>Order Checkout</h2>

@{
    List<SelectListItem> listOfStates = new List<SelectListItem>();

    listOfStates.Add(new SelectListItem { Text = "New South Wales", Value = "New South Wales" });
    listOfStates.Add(new SelectListItem { Text = "Queensland", Value = "Queensland" });
    listOfStates.Add(new SelectListItem { Text = "South Australia", Value = "South Australia" });
    listOfStates.Add(new SelectListItem { Text = "Tasmania", Value = "Tasmania" });
    listOfStates.Add(new SelectListItem { Text = "Victoria", Value = "Victoria" });
    listOfStates.Add(new SelectListItem { Text = "Western Australia", Value = "Western Australia" });
}

<div class="row">
    <div class="col-md-8">
        <h4>Please enter your shipping details and billing information.</h4>
        <hr />
        @using (@Html.BeginForm("OrderCheckout", "Checkout", FormMethod.Post, new { @class = "form-horizontal", id = "form" }))
        {
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.AntiForgeryToken()

            <h4>Shipping Details</h4>

            <div class="form-group">
                @Html.LabelFor(model => model.fullName, "Full Name", new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextBoxFor(model => model.fullName, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.fullName, "", new { @class = "text-danger" })
                </div>
            </div>
            
            <div class="form-group">
                @Html.LabelFor(model => model.streetAddress, "Street Address", new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextBoxFor(model => model.streetAddress, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.streetAddress, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.city, "City", new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextBoxFor(model => model.city, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.city, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.state, "State", new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.state, listOfStates, "-- Select Your State --", new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.state, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.postcode, "Postcode", new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextBoxFor(model => model.postcode, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.postcode, "", new { @class = "text-danger" })
                </div>
            </div>

            <br />

            <h4>Billing Information</h4>

            <div class="form-group">
                @Html.Label("Card Number", new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextBox("cc-number", "", new { @class = "form-control cc-number" }) 
                    <span id="cc-number-error" class="field-validation-error text-danger">Credit card number is not valid.</span>
                </div>
            </div>

            <div class="form-group">
                @Html.Label("Expiry Date", new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextBox("cc-exp", "mm/yyyy", new { @class = "form-control cc-exp" })
                    <span id="cc-exp-error" class="field-validation-error text-danger">Expiry date is not in a valid format.</span>
                </div>
            </div>

            <div class="form-group">
                @Html.Label("CVC", new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextBox("cc-cvc", "", new { @class = "form-control cc-cvc" })
                    <span id="cc-cvc-error" class="field-validation-error text-danger">CVC is not in a valid format.</span>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Confirm Order" class="btn btn-primary btn-bold" id="btnConfirm" />
                </div>
            </div>
        }       
    </div>
</div>

PartB/Views/Checkout/OrderSuccessful.cshtml
@model PartB.Models.Order

@{
    ViewBag.Title = "Thank you for your purchase!";
}

<h2>@ViewBag.Title</h2>

<hr />
<p>@Html.Encode(Session["FirstName"]), your order has been successfully placed!</p>
<p>
   Below is a summary of your order. 
   If there are any questions, please feel free to send us an email at 
   <a href="mailto:support@pcfakegear.com.au">support@pcfakegear.com.au</a>.     
   <br/>
   Thank you again for choosing PC Fake Gear and we hope to see you again soon! 
</p>
<br/>
<h4>Ship To:</h4>
<p>
    @Html.DisplayFor(model => model.fullName)
    <br/>
    @Html.DisplayFor(model => model.streetAddress)
    <br/>
    @Html.DisplayFor(model => model.city), @Html.DisplayFor(model => model.state)
    @Html.DisplayFor(model => model.postcode) 
</p>
<br/>
<h4>Order Summary</h4>
<br/>
<table class="table">
    <tr>
        <td><strong>Order ID: </strong>@Html.DisplayFor(model => model.orderID)</td>
        <td>&nbsp;</td>
        <td><strong>Order Date: </strong>@Html.DisplayFor(model => model.orderDate)</td>
    </tr>
    <tr>
        <th>Product Name</th>
        <th>Quantity</th>
        <th>Subtotal</th>
    </tr>
    @{
        if (!Model.itemList.Any())
        {
            <tr>
                <td>Nothing in here.</td>
            </tr>
        }
        else
        {
            foreach (var item in Model.itemList)
            {
                <tr>
                    <td>@item.productName</td>
                    <td>@item.productQty</td>
                    <td>@string.Format("{0:C}", @item.productSubtotal)</td>
                </tr>
            }
        }
    }
    
    <tr>
        <td colspan="3"><strong>Total:</strong> @string.Format("{0:C}", @Model.totalPrice)</td>
    </tr>
</table>
@using (Html.BeginForm("Index", "Home"))
{
    <p><input type="submit" value="&laquo; Back to Homepage" class="btn btn-primary btn-bold" /></p>
}