PartB/Controllers/CustomersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PartB.Models;
using System.Data.SqlClient;

namespace PartB.Controllers
{
    public class CustomersController : Controller
    {
        private StoreEntities db = new StoreEntities();

        // GET: Customers
        public ActionResult Index()
        {
            return RedirectToAction("Login");
        }

        public ActionResult Login()
        {
            return View();
        }
        
        // Login method sourced from Week 8 example code
        [HttpPost]
        public ActionResult Login([Bind(Include = "Email,Password")] Customer customer)
        {
            // Look up customer
            var login = db.Customers.FirstOrDefault(c => c.Email == customer.Email &&
                                                            c.Password == customer.Password);
            // If exists, set session variables
            if (login != null)
            {
                Session["Email"] = login.Email;
                Session["ID"] = login.ID;
                Session["FirstName"] = login.FirstName;
                Session["Cart"] = new Cart();

                return RedirectToAction("Index", "Home");
            }
            
            return View(customer);
        }

        public ActionResult Register()
        {
            return View();
        }

        // Logout method sourced from Week 8 example code
        public ActionResult Logout()
        {
            Session["Email"] = null;
            Session["ID"] = null;
            Session["FirstName"] = null;
            Session["Cart"] = null;

            return RedirectToAction("Login");
        }

        // Basically the Create method generated by VS2013 to add a new customer  
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Register([Bind(Include = "ID,FirstName,LastName,DateOfBirth,Email,Password,ConfirmPassword")] Customer customer)
        {
            // Check if email already exists
            var sameEmail = db.Customers.FirstOrDefault(c => c.Email == customer.Email);

            if (ModelState.IsValid)
            {
                if (sameEmail == null)
                {
                    db.Customers.Add(customer);
                    db.SaveChanges();

                    return RedirectToAction("RegisterSuccess");
                }
                else 
                {
                    TempData["error"] = "An account with this email address already exists.";
                    return View("Register");
                }
            }
            return View(customer);
        }

        public ActionResult RegisterSuccess()
        {
            return View();
        }
    }
}

PartB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - PC Fake Gear</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("PC Fake Gear", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Products", "Index", "Products")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Sitemap", "Sitemap", "Home")</li>
                </ul>
                @if (Session["Email"] != null)
                {
                    <ul class="nav navbar-nav navbar-right">
                        <li class="nav-text">Hello, <strong>@Html.Encode(Session["FirstName"])</strong>!</li>
                        <li>@Html.ActionLink("Your Cart", "Index", "Cart")</li>
                        <li>@Html.ActionLink("Log Out", "Logout", "Customers")</li>
                    </ul>
                }
                else
                {
                    <ul class="nav navbar-nav navbar-right">
                        <li>@Html.ActionLink("Register", "Register", "Customers")</li>
                        <li>@Html.ActionLink("Log in", "Login", "Customers")</li>
                    </ul>
                }                
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year PC Fake Gear. Created by John Le (s3401071) and Michael Abanilla (s3323163).</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>